USE [master]
GO

/****** Object:  Database [CacheDB]    Script Date: 3/3/2016 4:35:11 PM ******/
CREATE DATABASE [CacheDB] ON  PRIMARY 
( NAME = N'CacheDB', FILENAME = N'C:\MSSQL\DATA\CacheDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [ObjBLOB] 
( NAME = N'CacheDB_BLOB', FILENAME = N'C:\MSSQL\DATA\CacheDB_BLOB.ndf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ),
 FILEGROUP [CacheDB_mod] CONTAINS MEMORY_OPTIMIZED_DATA  DEFAULT
( NAME = N'CacheDB_mod1', FILENAME = N'C:\MSSQL\Data\CacheDB_mod1' )
 LOG ON 
( NAME = N'CacheDB_log', FILENAME = N'C:\MSSQL\DATA\CacheDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CacheDB] COLLATE Latin1_General_BIN2
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
---- create database with a memory-optimized filegroup and a container.
--ALTER DATABASE CacheDB ADD FILEGROUP CacheDB_mod CONTAINS MEMORY_OPTIMIZED_DATA 
--ALTER DATABASE CacheDB ADD FILE (name='CacheDB_mod1', filename='C:\MSSQL\Data\CacheDB_mod1') TO FILEGROUP CacheDB_mod 
ALTER DATABASE CacheDB SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT=ON
GO