USE [master]
GO
/****** Object:  Database [CacheDB]    Script Date: 7/29/2015 10:11:39 AM ******/
CREATE DATABASE [CacheDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CacheDB', FILENAME = N'C:\MSSQL\DATA\CacheDB.mdf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [ObjBLOB] 
( NAME = N'CacheDB_BLOB', FILENAME = N'C:\MSSQL\DATA\CacheDB_BLOB.ndf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 20480KB )
 LOG ON 
( NAME = N'CacheDB_log', FILENAME = N'C:\MSSQL\DATA\CacheDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CacheDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CacheDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CacheDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CacheDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CacheDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CacheDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CacheDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CacheDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CacheDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CacheDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CacheDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CacheDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CacheDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CacheDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CacheDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CacheDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CacheDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CacheDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CacheDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CacheDB] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [CacheDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CacheDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CacheDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CacheDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CacheDB] SET  MULTI_USER 
GO

ALTER DATABASE [CacheDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CacheDB] SET DB_CHAINING OFF 
GO
USE [CacheDB]
GO
/****** Object:  User [Anonymous]    Script Date: 7/29/2015 10:11:39 AM ******/
CREATE USER [Anonymous] FOR LOGIN [Anonymous] WITH DEFAULT_SCHEMA=[dbo]
GO
GRANT CONNECT TO [Anonymous] AS [dbo]
GO
